baseURL = "/"
languageCode = "en"
title = "Dantcho - Web Developer"
theme = "dantcho"
paginate = 10
disqusShortname = "dantcho"
googleAnalytics = "G-755WHB1MHP"

[params]
    author = "Yordan Hristov"
    description = "Yordan Hristov is a self taught web developer aka Dantcho. This is his web development blog."
    favicon = "favicon.ico"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[permalinks]
    posts = "/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"